name: CI Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Test
        run: echo 0

  require-label:
    if: ${{ github.event.label.name == 'qa-approved' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run a final test
        run: echo 0

  require-label-job:
    needs: [require-label, build]
    if: ${{ !success('build') || !success('require-label') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo -1
